### ISSUE TITLE
Create a route for download QRCode image and save the device id associated

### ISSUE THREAD

**Issue by WTFlay** [TristanMarion/Jerrol-API#19]

**Comment by TristanMarion** [comment]
If I understand the need, you want a route like `GET /qrcode?code=JERRY` which generates a QRCode with a code used to call the `POST /users/:user_id/devices` ?

**Comment by WTFlay** [comment]
No, I want a route which download a image from user app and read the Code associated to QR code for post device for user.

**Comment by WTFlay** [comment]
The QRCode will be read by app and the value will be send to API on /users/{userId}/devices
