### ISSUE TITLE
State device routes (GET, PUT & DELETE) 

### ISSUE THREAD

**Issue by WTFlay** [TristanMarion/Jerrol-API#21]
The route can be: `/devices/{deviceId}/state`

Only GET, PUT and DELETE are available.

DELETE can be use for signal when the device power-off.

**Comment by WTFlay** [comment]
The input and output data can be like that:
```json
{
  "humidity": 40,
  "sun": "true",
  "light": "false"
}
```

**Comment by TristanMarion** [comment]
Done in #29
