### ISSUE TITLE
[Proposal] Refacto of alerts/notifications system

### ISSUE THREAD

**Issue by TristanMarion** [TristanMarion/Jerrol-API#22]
What about a new system for alerts and notifications like the ones existing in development for logging :
- `INFO`: for current notifications (light has been switched on/off)
- `WARN` : for current alerts (needs water or too much light)
- `ERROR` : TBD (maybe a device crash, or something really bad (0% humidity?))

The messages would have this data schema : 
```JSON
{
  "deviceId": "deviceId",
  "type": "INFO",
  "code": "LIGHT_ON",
  "message": "info.light.switched-on"
}
```

And it would works like for notifications and alerts : a `GET` route to get device messages, a `POST` route to create messages. Same system than the existing one for the dates, using the timestamp stored in Mongo ID.

**Comment by WTFlay** [comment]
@TristanMarion I think the message can't be a literal string but should be a message code like: `info.light.turn-on`.
Hence, it will be more easily to translate message in front app.

**Comment by TristanMarion** [comment]
You would like to concatenate everything in a single field ?
LGTM and it well be translating compliant for future versions of the app !

**Comment by WTFlay** [comment]
No no, not concatenate. Just the message with a specific code for easily bind message :)
We keep `type` and `code`.

**Comment by TristanMarion** [comment]
Ok let's do that :D

**Comment by TristanMarion** [comment]
Done in #28
